In [4]:
from typing import Protocol, List, Tuple, Dict
import numpy as np
from sklearn.model_selection import ShuffleSplit


"""TEST 1 (The original code)"""
class CROSS_VAL_FN(Protocol):
    def __call__(self,
                 num_splits: int,
                 indices: np.ndarray) -> List[Tuple[np.ndarray, np.ndarray]]:
        ...
        

def cv1(num_splits: int, indices: np.ndarray) -> List[Tuple[np.ndarray, np.
    ndarray]]: 
    cv = ShuffleSplit(n_splits=num_splits) 
    splits = list(cv.split(indices)) 
    return splits


cvs: Dict[str, CROSS_VAL_FN] = {"cv1": cv1}
cvs["cv1"](3, np.arange(10))

[(array([7, 6, 2, 5, 9, 1, 0, 8, 3]), array([4])),
 (array([1, 2, 5, 4, 6, 9, 0, 8, 7]), array([3])),
 (array([7, 0, 9, 3, 4, 6, 5, 1, 8]), array([2]))]

[(array([6, 0, 3, 7, 5, 9, 4, 1, 8]), array([2])),
 (array([3, 9, 0, 4, 1, 7, 5, 2, 6]), array([8])),
 (array([3, 8, 1, 4, 9, 5, 2, 7, 6]), array([0]))]

In [ ]:
"""TEST 3 (expected usage of Protocol)"""
def cv_func(cv: CROSS_VAL_FN, **kwargs):
    cv(**kwargs)